# Generated by Django 4.1.3 on 2023-01-09 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_file', models.FileField(upload_to='')),
                ('summary', models.TextField(max_length=3000)),
                ('introduced', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('bill_type', models.CharField(choices=[('lagisation', 'Lagisation'), ('bill', 'Bill')], max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('first_election', models.CharField(blank=True, max_length=255)),
                ('next_election', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('party', models.CharField(blank=True, choices=[('republican', 'Republican'), ('democrat', 'Democrat')], max_length=255)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2550)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('aey', 'Aey')], max_length=255)),
                ('state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('NewHampshire', 'NewHampshire'), ('NewJersey', 'NewJersey'), ('NewMexico', 'NewMexico'), ('NewYork', 'NewYork'), ('NorthCarolina', 'NorthCarolina'), ('NorthDakota', 'NorthDakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('RhodeIsland', 'RhodeIsland'), ('SouthCarolina', 'SouthCarolina'), ('SouthDakota', 'SouthDakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=255)),
                ('party', models.CharField(choices=[('republican', 'Republican'), ('deemocrat', 'Democrat'), ('indipendent', 'Indipendent')], max_length=255)),
                ('description', models.TextField(max_length=2550)),
                ('short_text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('repersentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_education.moc')),
            ],
        ),
        migrations.CreateModel(
            name='VotingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('votes', models.ManyToManyField(to='policy_education.votes')),
            ],
        ),
        migrations.CreateModel(
            name='UserVotingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_education.votingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sponsor', 'Sponsor'), ('co-sponsor', 'Co-Sponsor')], max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_education.bill')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_education.moc')),
            ],
        ),
        migrations.CreateModel(
            name='SavedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_education.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillSubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('_type', models.CharField(choices=[('bijainagar', 'bijainagar'), ('goa', 'Goa')], max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sub_topics', models.ManyToManyField(blank=True, to='policy_education.billsubjectarea')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_education.status'),
        ),
        migrations.AddField(
            model_name='bill',
            name='subject_areas',
            field=models.ManyToManyField(to='policy_education.billsubjectarea'),
        ),
    ]
